### ISSUE TITLE
Provide scan codes in input events

### ISSUE THREAD

**Issue by joar** [PistonDevelopers/piston#1143] opened 2017-01-10 10:03 UTC
Scan codes refer to the physical location of the key on a QWERTY keyboard disregarding any customizations or cultural variations.

Dramatized example:

> A developer using the QWERTY layout has made a game, the game listens for the W, A, S, D "letters" (SDL_Keycodes) in order to move forward, left, backward, right. A potential player of that game lives in France, and uses the [AZERTY keyboard layout](https://en.wikipedia.org/wiki/AZERTY). She starts the game and tries to move forward, but nothing happens. A second potential player uses the [Dvorak keyboard layout](https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard), she can only move to the left. A third potential player has created her own layout, she can't move at all.
> 
> If the players are lucky, the developer has provided a way to rebind keys, and the users will have to go through that to fix any differences between their layout and the developer's layout.
>
> If the game had listened for the W, A, S, D "keys" (SDL_Scancode), the users would have been able to move around and explore the game right from the start.

Disclaimer: I barely know any rust at all, but i wanted to start learning it using piston, just to get annoyed by this issue since I use [Svorak](https://en.wikipedia.org/wiki/Dvorak_Simplified_Keyboard#Svorak).

My impression is that the `Button` type should provide both the "text" meaning of the button pressed and the "key" meaning of the button pressed. In the case of AZERTY this would be `Button { key: "Q", char: "A" }` for the top-left button on the keyboard.

It seems that at least SDL2 emits Button events with both the "text" (SDL_Keycode) meaning and the "key" (SDL_Scancode) meaning attached.

Resources:
- [How can I handle different keyboard layouts?](http://gamedev.stackexchange.com/questions/53064/how-can-i-handle-different-keyboard-layouts)
- [An enumeration of the SDL keyboard scancode representation ](https://wiki.libsdl.org/SDL_Scancode)

**Comment by bryanbecker** [comment] 2017-06-17 01:03
@lucklove  I see this as more of an error needing fixing rather than an enhancement.

Press and release events are broken on my keyboard.  I use dvorak layout, so normally when I press `s` on my keyboard, 'o' is typed on the screen.  You could say that's working as intended, but if I change my keyboard layout to the US sub-layout like I normally would do for games, Piston doesn't react.

I still get ",aoe" instead of the expected "asdf" read by piston, _even though my keyboard layout is US_

This is definitely an error, as Piston should either return the scan code (the code associated with the physical button on the keyboard), or the key code (the character obtained by pressing the key) ... or ideally both.

----

1) My default keyboard layout is Dvorak
2) I switch to US layout (before running the bin or during... doesn't matter).
3) I push the 's' key on my keyboard.
4) Piston interprets an 'o'

Expected:  Piston interprets an 's' like everything else on my computer

----

There's two parts here:
1 - As per above, ideally scancode and keycode should both be emitted in the event
2 - Piston seems to be incorrectly reading keycodes from the system

**Comment by bvssvni** [comment] 2017-06-17 18:56
Somebody who want to help fixing this? I'll create a todo-list in the meantime.

- [ ] Do we need a new `ScanCode` enum in pistoncore-input?
- [ ] Add new `AdvancedPress` and `AdvancedRelease` event traits for backward compatibility?
- [ ] Update [user-input](https://github.com/PistonDevelopers/piston-examples/tree/master/user_input) to test scan codes

**Comment by bvssvni** [comment] 2017-08-20 17:29
One idea is to add a new `ButtonEvent` which has more arguments than `PressEvent` and `ReleaseEvent`. The scancode can be stored in a `ButtonArgs` struct such that `Button` still works with equality checks.

**Comment by bvssvni** [comment] 2017-08-21 17:18
Closed by https://github.com/PistonDevelopers/piston/pull/1195

**Closed by bvssvni** 2017-08-21 17:18 UTC
Labels: enhancement
