### ISSUE TITLE
Rendered window bigger than specified size

### ISSUE THREAD

**Issue by Ironmaggot** [PistonDevelopers/piston#1200] opened 2017-08-28 16:42 UTC
When using WindowSettings::new() to create a window, the displayed window size is bigger than the size entered into the WindowSettings::new() size argument.

In other words. My monitor resolution is 1920x1080. Creating a window with the same size will result in a window which is larger than my screen. For example, if I create a window the size of 900x900, then the displayed window does not fit on the screen with its height. Displayed 900x900 window is taller than my 1080 tall monitor.

**Comment by bvssvni** [comment] 2017-08-28 20:13
Which OS and window backend?

**Comment by Ironmaggot** [comment] 2017-08-29 08:53
Oh,  yes, forgot to mention it.  It's Win 10.

**Comment by Ironmaggot** [comment] 2017-08-29 16:32
About the backend I am not sure - its the default backend, I guess.

Here's the entirety of the code.

```rust
extern crate piston_window;

use piston_window::*;

fn main() {
    let mut window: PistonWindow =
        WindowSettings::new("Hello Piston!", [900, 900])
        .decorated(false).exit_on_esc(true).build().unwrap();
    while let Some(event) = window.next() {
        window.draw_2d(&event, |context, graphics| {
            clear([1.0; 4], graphics);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [400.0, 700.0, 100.0, 100.0],
                      context.transform,
                      graphics);
        });
    }
}
```

**Comment by varomix** [comment] 2018-12-02 03:33
Hi, was this solved
I have the same issue on Linux
![image](https://user-images.githubusercontent.com/728059/49335289-13c83980-f5a8-11e8-818a-7f61c0183775.png)
I measured it with the screen tool and is WAY bigger that specified, I noticed the same with other peoples Piston projects, the windows are bigger.

thanks

**Comment by lwiklendt** [comment] 2018-12-03 05:56
I think the issue might be due to lack of HDPI support in the default backend. Try using the GLFW backend:

```rust
extern crate piston_window;
extern crate glfw_window;
use glfw_window::GlfwWindow;
use piston_window::*;

fn main() {
    let mut window: PistonWindow<GlfwWindow> =
        WindowSettings::new("Hello Piston!", [900, 900])
            .decorated(false).exit_on_esc(true).build().unwrap();
    while let Some(event) = window.next() {
        window.draw_2d(&event, |context, graphics| {
            clear([1.0; 4], graphics);
            rectangle([1.0, 0.0, 0.0, 1.0], // red
                      [400.0, 700.0, 100.0, 100.0],
                      context.transform,
                      graphics);
        });
    }
}

```

**Comment by varomix** [comment] 2018-12-03 05:58
I found out the issue is Glutin so I did change that GLFW and that works

thanks

**Comment by vwood** [comment] 2020-03-10 12:27
It's "cargo add pistoncore-glfw_window" for anyone coming to this party.

**Comment by bvssvni** [comment] 2024-05-21 22:15
Closing. Reopen if this is still an issue.

**Closed by bvssvni** 2024-05-21 22:15 UTC
