### ISSUE TITLE
Borderless Windows

### ISSUE THREAD

**Issue by yeliknewo** [PistonDevelopers/piston#1025] opened 2016-01-05 16:56 UTC
Borderless fullscreen windows that can lock the mouse inside the window unless you tab out are very important for multi monitor gaming. The current fullscreen seems to be very buggy for me. Could we scrap normal fullscreen for borderless fullscreen?

**Comment by bvssvni** [comment] 2016-01-05 20:05
Can you explain what kind of buggy behavior you experience?

**Comment by yeliknewo** [comment] 2016-01-05 22:22
Sometimes when I launch it my monitor gets turned off in the operating system settings. Other times the resolution changes and doesn't change back when I tab out or exit the game.

**Comment by bvssvni** [comment] 2016-01-06 15:06
Wow! That sounds like a bug caused by unsafe behavior. Perhaps it is the graphics driver?

**Comment by bvssvni** [comment] 2024-04-30 17:50
Closing.

**Closed by bvssvni** 2024-04-30 17:50 UTC
Labels: question
