### ISSUE TITLE
Fullscreen changes the resolution but does not restore it after quit

### ISSUE THREAD

**Issue by dns2utf8** [PistonDevelopers/piston#1125] opened 2016-11-06 00:36 UTC
I was realy amazed how smoth it was to create a simple window, congratulations :+1: 

When I tried it I noticed after the fullscreen my resolution stayed the same.
Did I miss a flag or is this a bug?

Regards

**Comment by bvssvni** [comment] 2016-11-06 00:39
You need to resize the frame buffer. See https://github.com/PistonDevelopers/piston_window/blob/master/src/lib.rs#L273

**Comment by BedfordWest** [comment] 2017-03-07 03:18
I spent a good amount of time trying to sort through this over the past week or so, and I'm still a little lost. From the best I can tell, this issue is caused by a combination of xorg not restoring resolution to what it was prior to running a process that changes it (see (https://bugs.freedesktop.org/show_bug.cgi?id=14255)) and GlutinWindow not handling this behavior by default.

Does (https://github.com/PistonDevelopers/piston/issues/1125#issuecomment-258652263) indicate that we should be able to track the pre-fullscreen resolution and then restore it before exiting the program by setting output_stencil equal to the original value? If so, any tips for how this can be done?

**Comment by bvssvni** [comment] 2017-03-07 12:40
I interpreted this differently. I thought the problem was running a fullscreen application in desktop resolution. Currently the resolution you pass to `WindowSettings::new` is the one used in fullscreen mode.

So the problem is the desktop resolution changing after running a fullscreen application?

**Comment by BedfordWest** [comment] 2017-03-07 13:53
That's correct - the problem I am able to reproduce is the desktop resolution changing to match the WindowSettings resolution and not changing back after the process ends if the window's fullscreen setting is true.

**Comment by BedfordWest** [comment] 2017-03-07 14:48
Example:
My desktop resolution on i3 with xrg is 1920x1080 . I run my game, which creates a new PistonWindow from WindowSettings with fullscreen(true) and resolution 1280x720. The game will correctly display this resolution, but upon pressing ESC to close the window or setting window_should_close to true, the game will exit, and my desktop will now remain in 1280x720.

**Comment by bvssvni** [comment] 2017-03-07 14:53
One problem is that we can't do this in glutin_window. If you press ESC and there is outer loop that sets `should_close` back to `false`, then changing the desktop resolution will result in the game continue running with another resolution.

**Comment by bvssvni** [comment] 2024-04-30 18:42
Closing as outdated. Feel free to open a new issue.

**Closed by bvssvni** 2024-04-30 18:42 UTC
Labels: question
