### ISSUE TITLE
Split organisation into groups that will have access only to given repos

### ISSUE THREAD

**Issue by hauleth** [PistonDevelopers/piston#851] opened 2015-03-09 17:16 UTC
For now there is kind of Wild Wild West and anybody has access to all repos. It will be easier if community will be spliced into smaller groups that will have access only to one repo. Also it could be nice if there would be group that will contain all contributors (so they could attach badge to their GH account), but they will have no write access, nowhere.

Reasoning:
- we have pull-requests - people doesn't need to have write access
- people has different codestyle, but project should has one guidelines. With pull requests it became possible
- code review
- better CI messages

Just do review who has spine and some brain cells in right places and disallow making mess in all repos. Only a few can blew up everything with enough grace that it can be called art.

@bvssvni, @mitchmindtree

**Comment by bvssvni** [comment] 2015-03-10 11:25
In game theory, there is something called "Nash equilibrium" which is how people choose their actions depending on the cost/benefits they get from participating in a game.

Giving everyone write access is the essential strategical move that shifts the Nash equilibrium to "do your best". It is one of the things that makes it possible for everyone to step in and help, which motivates people to join.

There are potential benefits from changing this strategy, but those are strictly non-human, and they are assumed that humans work like machines without failure. The problem is that the human brain has much deeper flaws that this level, and it needs a proper sophisticated model of the entire picture, which involves the maintainers risk for burnout and the ability to take vacations without warnings. If you can picture the connections then you're good at big picture thinking, but trust me when I say this is a much harder problem than it seems to be on the surface, and I've put some effort last summer working out what to do.

There are indications that spending more time in code review leads to less productivity and artificial motivation to "get accepted" their changes as the driving force of work, instead of contributing that effort into the planning phase.

I'm not putting this forth as a criticism of other projects, but the Piston philosophy works at an entire different level of thinking (involving a lot more factors) and as far as I am concerned, the non-human benefits are not worth being concerned about, compared to the actual costs of emotional stress both maintainers and contributors have to go through when working on a strict code review process, or restricted access to different repositories. That gets in the way of productivity, and the amount of hours wasted on this isn't worth it.

**Comment by mitchmindtree** [comment] 2015-03-10 11:59
After being a part of Piston and watching it grow over the last year I've been really impressed with how smoothly everything runs, despite having such a large number of contributors. I was also originally skeptical of the free-for-all approach, but honestly I haven't personally experienced a single substantial issue from it. The following are some things I've noticed:
- A sense of community, equality and freedom has developed.
- People are almost never blocked by having to wait for an admin to accept a PR (this is a big plus, especially when 90% of PRs are maintenance and subtle tweaks during Rust's growing pains. It's simply not practical to have only a select few people try and keep track of all of this).
- If there are any possibly controversial changes to be made, they are always left in a PR for review anyway.
- There are more eyes on more project.
- Cross-pollination of projects has become slightly easier.

**Comment by indiv0** [comment] 2015-03-10 12:26
:+1: for everything stated by @mitchmindtree & @bvssvni.

I think the pseudo-anarchy setup currently in place is perfect for the project because it provides a minimal barrier to quick, iterative progress on all projects, while still allowing for easy tracking of development progress (workflow via PRs, issues, etc.).

Adding additional barriers to development seems unnecessary to me.

**Comment by hauleth** [comment] 2015-03-10 12:52
Main reason, why I wanted this is commit PistonDevelopers/image@64fc315b. Just compare it with the same commit, when all whitespace changes are hidden - [diff](https://github.com/PistonDevelopers/image/commit/64fc315b48ab809346afa775235574b2e19248bc?w=1). For now there is no style checker like HoudCI that will fix that. `rustfmt` is still missing and most of styling issues could be prevented just by simple review. Also sometimes I have feel that some code is duplicated for no reason (to be honest - there is reason, someone lacks a method and write it in place and do not think about extracting it into another module - via PistonDevelopers/image#247 or [that macros](https://github.com/hauleth/image/commit/7105dc11fcdb7ae04d733890a287e056f93e6f11?diff=unified#diff-df6bcf4635b713c31712766022cc3563L66)). That are minor issues, but IMHO the problem will only grow. I don't know how many other places has duplicated code or other styling issues.

There are a lot good thinks that happen thanks this development model, but if we don't tame this now then in some time we finish with something like X11. Overbloated thing, with a lot of weirdos, repeated features with different names and so on. I really like this project and I don't want to see that this is falling apart. For now there should be elected "project leaders" that will manage how given part will move on. Rust is stabilising so Piston development should also, otherwise in some time there would be no one who would fix things (or even can fix them).

**Comment by bvssvni** [comment] 2015-03-10 21:05
@hauleth If you open issues about these concerns, then it will be easier for other people to discuss it in the right context. It is very common that I or somebody else have a specific problem and see this as part of a bigger picture, but in retrospect it was often solved by going through the iterations of narrowing the problem to the essential parts. For style guidelines, we'll use automated tools when they are ready, see https://github.com/PistonDevelopers/piston/issues/844

In general, I think that the Piston philosophy works great in this case, because people usually only fork the projects they need, and all changes are recommended doing through PRs. When `rustfmt` comes much of these problem will be fixed.

The piston-image project is somewhat an exception, because the project is relatively large compared to the typical piston library. So if you can keep an eye out on this problem, and remind us about it, it would be very helpful.

Rereading your original post in this context I can easily get the point, but I think it is irrelevant to the general philosophy. For this reason, I will close this discussion and recommend addressing these issues directly.

**Closed by bvssvni** 2015-03-10 21:05 UTC
Labels: discussion
